### ISSUE TITLE
Minecraft Crash Exit Code 1

### ISSUE THREAD

**Issue by Leichenengel** [HiWord9/CITResewnNeoPatcher#2]
Hello :)

I just downloaded this with all dependencies (unless I already had them anyways). I run on the latest 1.21.1 NeoForge Build with all dependencies also on the latest builds for 1.21.1. Same goes for my other mods. Now that I added your mod to my list. Minecraft crashes only giving the Exitcode 1.
I'd post a logfile but the latest one I have is from days ago. Not sure why it doesn't log one for the crash.
This also shouldn't conflict with other mods (unless it's not compatible with Sodium or ModernFix). Ofc I also use other mods like Terralith, Oh the biomes we've gone and Farming mods and a ton of small QoL mods. Before I added this mod and its dependencies (excluding the optional ones) my game crashes a few seconds into the loading process of NeoForge. After Removing this mod and CIT Resewn everything works again.

If you want a full modlist to reproduce this let me know :)

Cheers!

**Comment by HiWord9** [comment]
Can't do much without logs, try to reproduce the crash and check the ``.minecraft/logs/latest.log``, mb removing everything from logs folder will help in case it cant be saved.
In case this does not work, then please do as described below: In minecraft laucher go to settings -> under Minecraft: Java Edition Settings: Open output log when Minecraft: Java Edition starts. This will open the log window on game strart, after crash u can copy its content and paste here (better if u send it here as txt file).

Logs are very important cause i need to inspect this case. At least mods list, but

**Comment by HiWord9** [comment]
Can't do much without logs, try to reproduce the crash and check the .minecraft/logs/latest.log, mb removing everything from logs folder will help in case it cant be saved.
In case this does not work, then please do as described below: In minecraft laucher go to settings -> under Minecraft: Java Edition Settings: Open output log when Minecraft: Java Edition starts. This will open the log window on game strart, after crash u can copy its content and paste here (better if u send it here as txt file).

Logs are very important cause i need to inspect this case. At least mods list, but having only mods it may take a lot of time for me to figure it out.

**Comment by Leichenengel** [comment]
Right - have been thinking about using the console myself yesterday but got distracted XDD

There you go. I hope that helps :)

[MC-Gameoutput.txt](https://github.com/user-attachments/files/18038618/MC-Gameoutput.txt)

**Comment by HiWord9** [comment]
Thanks for provided exception report. I see that program fails to read some file located in mods folder, it's not necessary cit resewn jar, it may be any other file, i think i will make it ignore such cases but i still need to figure out what exactly causes it. Unfortunatelly crash report does not contain info about loaded mods and everything else that may help me inspect this. Please tell me: what OS u are using? what are mods u are playing with?and is there any other files in mods dir? Btw the normal log (without cit resewn neopatcher) likely will contain OS specs and everything, so u may just send that.

**Comment by HiWord9** [comment]
Just published 1.1.0 which should fix this. If doesn't, reopen the issue. Thanks for the report!

**Comment by Leichenengel** [comment]
Hello, I tried out the 1.1.0 and the issue persists or rather is now different but similar.

![citresewn-neopatcher-screen](https://github.com/user-attachments/assets/2830bfa8-fc4e-4aab-8ad8-729414a3a336)

https://gist.github.com/Leichenengel/47f886d467e5e8f163bf9ef765dc38bf
This ist the latest.log. It should contain a list of all the mods I have installed (for some reason the Sinatra Connector is not listed even though I definitely have it installed - it even created a .connector folder within the mod folder.

https://gist.github.com/Leichenengel/979261560876187aaf9225cf70acf760
This is the related Crash Report which also contains my OS and hardware infos.

I hope this helps. I'm gonna continue playing without this, so take your time :)

**Comment by kran27** [comment]
I believe i've found the solution. changing "enableMixinSafeguard" to false in the sinytra config file (`config/connector.json`) made it load properly for me.

**Comment by HiWord9** [comment]
@kran27 I think it may be due to outdated connector cache, which may be should be updated to solve this.
Could u please test it seting "enableMixinSafeguard" back to true and launching the game again? It would help determine if this setting realy matters or is it just triggering updatign the cache.

**Comment by Leichenengel** [comment]
I will try this as soon as I have my setup running again. I updated neoforge yesterday and now the game just crashes when loading. Already contacted the folks over there so hopefully it can be resolved soon.
